### PR TITLE
Fix renaming attributed class members

### LINKED ISSUE #2577: Cannot rename property or method if its definition contains any attribute
```php
<?php

namespace Arctgx\PhpactorAttrCompletion;

use Override;

class Details
{
    #[Override]
    private $foo;

    #[ReturnTypeWillChange]
    public function getFoo()
    {
        return $this->foo;
    }
}
```
Trying to rename `$foo` in the above example I get `LSP Message (phpactor) Could not find corresponding reference to member name "foo" in document "file:///home/arctgx/dev/arctgx/php/phpactor-attr-completion/src/Details.php" at offset 84`. The same exception I get when trying to rename method with attribute. 

https://github.com/phpactor/phpactor/blob/5da647cd525f04c41f2ded6678f44844c58114c8/lib/Rename/Adapter/ReferenceFinder/AbstractReferenceRenamer.php#L81-L89

The example is simplified as much as possible. In practice it was ORM column attribute.

### PR DESCRIPTION
**Pull request by przepompownia**
Fix #2577

### CODE REVIEW

**Comment by dantleech** [comment]
is this a parser bug though? and if not does the same apply to properties?

**Comment by przepompownia** [comment]
It seems to be ready to review for class members.

**Review by dantleech — APPROVED** [review]

**Comment by dantleech** [comment]
thanks!

**Comment by przepompownia** [comment]
Thank you especially for [the hint](https://github.com/phpactor/phpactor/issues/2577#issuecomment-2027025787) - it significantly reduced investigating.

**Pull request merged**
