### PR TITLE
Add snippet to type suggestions for object creation

### PR DESCRIPTION
**Pull request by przepompownia**

### CODE REVIEW

**Comment by dantleech** [comment]
:bow:

**Comment by przepompownia** [comment]
Thanks. I thought about adding exclusion if the next node is an existing parameter list (to avoid adding duplicated parens) but it can be done separately.

**Comment by dantleech** [comment]
Just a heads up - I may revert this. It makes a mess when replacing an existing isntantiation

```
new Foobar();
```

I want to change it to:

```
new Barfo<>()
```

but it's then completed as:

```
new Barfoo()()
```

**Comment by dantleech** [comment]
Edit I opened the PR above to revert the revert.

**Pull request merged**
