### PR TITLE
Fix documentation typo

### PR DESCRIPTION
**Pull request by allendoerfer**

### CODE REVIEW

**Comment by dantleech** [comment]
Hi, this document is auto generated, so not sure what's happened here..

**Comment by mamazu** [comment]
The error is in the file `lib/Extension/LanguageServer/LanguageServerExtension.php` at line 100. However, if we change the code this is technically going to be a bc breaks which should also be mentioned in the `UPGRADE.md` file.

**Comment by dantleech** [comment]
It's correct documentation, there is a typo in the code:

https://github.com/phpactor/phpactor/blob/f9c74b7121919c9d088baea712fa8956dfad5122/lib/Extension/LanguageServer/LanguageServerExtension.php#L100

**Comment by allendoerfer** [comment]
I changed the mentioned file and added a line to the `CHANGELOG.md`, because I could not find an `UPGRADE.md` file.

**Comment by dantleech** [comment]
Thanks!

**Pull request merged**
