### PR TITLE
Complete inside attribute parameter value

### PR DESCRIPTION
**Pull request by przepompownia**

### CODE REVIEW

**Comment by przepompownia** [comment]
I suspect it's not the correct way to such completion - please close it if there is any better way. 

I have a look into `WorseParameterCompletor` but at the moment have no idea how to deal with attribute there.

**Comment by przepompownia** [comment]
It does not restrict any result to constants or values.

**Comment by dantleech** [comment]
:wave: can you add a description about what this does and why?

**Comment by przepompownia** [comment]
I could not get such completion, but now I can on master:

image

Let me verify it later.

**Comment by dantleech** [comment]
Maybe due to (mostly fixed) regressions with class filtering

**Pull request closed without merging**
