### PR TITLE
Fix crash on MissingToken

### PR DESCRIPTION
**Pull request by vlada-dudr**
Little fix for a crash occuring during indexing on some weird projects.

### CODE REVIEW

**Comment by vlada-dudr** [comment]
Phpstan doesn't like it, but obviously type annotation in PhpParser is wrong, otherwise it wouldn't crash on me with
```
PHP Fatal error:  Uncaught Error: Call to undefined method Microsoft\PhpParser\MissingToken::getResolvedName() in /home/vladimir/devel/phpactor/lib/Indexer/Adapter/Tolerant/Indexer/ClassDeclarationIndexer.php:59
Stack trace:
#0 /home/vladimir/devel/phpactor/lib/Indexer/Adapter/Tolerant/Indexer/ClassDeclarationIndexer.php(28): Phpactor\Indexer\Adapter\Tolerant\Indexer\ClassDeclarationIndexer->indexBaseClass()
#1 /home/vladimir/devel/phpactor/lib/Indexer/Adapter/Tolerant/TolerantIndexBuilder.php(80): Phpactor\Indexer\Adapter\Tolerant\Indexer\ClassDeclarationIndexer->index()
#2 /home/vladimir/devel/phpactor/lib/Indexer/Adapter/Tolerant/TolerantIndexBuilder.php(93): Phpactor\Indexer\Adapter\Tolerant\TolerantIndexBuilder->indexNode()
#3 /home/vladimir/devel/phpactor/lib/Indexer/Adapter/Tolerant/TolerantIndexBuilder.php(67): Phpactor\Indexer\Adapter\Tolerant\TolerantIndexBuilder->indexNode()
#4 /home/vladimir/devel/phpactor/lib/Indexer/Model/IndexJob.php(28): Phpactor\Indexer\Adapter\Tolerant\TolerantIndexBuilder->index()
#5 /home/vladimir/devel/phpactor/lib/Indexer/Extension/Command/IndexBuildCommand.php(85): Phpactor\Indexer\Model\IndexJob->generator()
#6 /home/vladimir/devel/phpactor/lib/Indexer/Extension/Command/IndexBuildCommand.php(56): Phpactor\Indexer\Extension\Command\IndexBuildCommand->buildIndex()
#7 /home/vladimir/devel/phpactor/vendor/symfony/console/Command/Command.php(298): Phpactor\Indexer\Extension\Command\IndexBuildCommand->execute()
#8 /home/vladimir/devel/phpactor/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#9 /home/vladimir/devel/phpactor/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#10 /home/vladimir/devel/phpactor/lib/Application.php(46): Symfony\Component\Console\Application->doRun()
#11 /home/vladimir/devel/phpactor/vendor/symfony/console/Application.php(171): Phpactor\Application->doRun()
#12 /home/vladimir/devel/phpactor/bin/phpactor(45): Symfony\Component\Console\Application->run()
#13 {main}
  thrown in /home/vladimir/devel/phpactor/lib/Indexer/Adapter/Tolerant/Indexer/ClassDeclarationIndexer.php on line 59
Fatal error: Uncaught Error: Call to undefined method Microsoft\PhpParser\MissingToken::getResolvedName() in /home/vladimir/devel/phpactor/lib/Indexer/Adapter/Tolerant/Indexer/ClassDeclarationIndexer.php:59
Stack trace:
#0 /home/vladimir/devel/phpactor/lib/Indexer/Adapter/Tolerant/Indexer/ClassDeclarationIndexer.php(28): Phpactor\Indexer\Adapter\Tolerant\Indexer\ClassDeclarationIndexer->indexBaseClass()
#1 /home/vladimir/devel/phpactor/lib/Indexer/Adapter/Tolerant/TolerantIndexBuilder.php(80): Phpactor\Indexer\Adapter\Tolerant\Indexer\ClassDeclarationIndexer->index()
#2 /home/vladimir/devel/phpactor/lib/Indexer/Adapter/Tolerant/TolerantIndexBuilder.php(93): Phpactor\Indexer\Adapter\Tolerant\TolerantIndexBuilder->indexNode()
#3 /home/vladimir/devel/phpactor/lib/Indexer/Adapter/Tolerant/TolerantIndexBuilder.php(67): Phpactor\Indexer\Adapter\Tolerant\TolerantIndexBuilder->indexNode()
#4 /home/vladimir/devel/phpactor/lib/Indexer/Model/IndexJob.php(28): Phpactor\Indexer\Adapter\Tolerant\TolerantIndexBuilder->index()
#5 /home/vladimir/devel/phpactor/lib/Indexer/Extension/Command/IndexBuildCommand.php(85): Phpactor\Indexer\Model\IndexJob->generator()
#6 /home/vladimir/devel/phpactor/lib/Indexer/Extension/Command/IndexBuildCommand.php(56): Phpactor\Indexer\Extension\Command\IndexBuildCommand->buildIndex()
#7 /home/vladimir/devel/phpactor/vendor/symfony/console/Command/Command.php(298): Phpactor\Indexer\Extension\Command\IndexBuildCommand->execute()
#8 /home/vladimir/devel/phpactor/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#9 /home/vladimir/devel/phpactor/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#10 /home/vladimir/devel/phpactor/lib/Application.php(46): Symfony\Component\Console\Application->doRun()
#11 /home/vladimir/devel/phpactor/vendor/symfony/console/Application.php(171): Phpactor\Application->doRun()
#12 /home/vladimir/devel/phpactor/bin/phpactor(45): Symfony\Component\Console\Application->run()
#13 {main}
  thrown in /home/vladimir/devel/phpactor/lib/Indexer/Adapter/Tolerant/Indexer/ClassDeclarationIndexer.php on line 59
```

**Comment by dantleech** [comment]
yes, the types in the parser (the tolerant PHP parser) are often wrong. feel free to add `/** @phpstan-ignore-next-line */

**Comment by vlada-dudr** [comment]
Here you go.

**Comment by dantleech** [comment]
merci!

**Pull request merged**
