### PR TITLE
2020 11 22

### PR DESCRIPTION
**Pull request by dantleech**
```
    [2020-11-21 10:04:32] a2789e00 web-flow fix properties inferred types (#73)  * fix properties inferred types    * fix smoke test error on the CI    * updat...
    [2020-11-21 17:31:11] b8596002 web-flow Extract properties and methods from class' traits (#74)
    [2020-11-22 19:30:32] af58fccb web-flow Test performance regressions
    with PHPBench
```

### CODE REVIEW

**Comment by dantleech** [comment]
image

@camilledejoye although the `$this` issue seems fixed, properties still do not have inferred types -- is this what you expect?

**Comment by camilledejoye** [comment]
I noticed this too but I was not sure how to interpret it.
The type show here is the "best" type I guess, we only return one type to the LSP client.
But if you try to complete `$this->foo->` the public members from `FooBar` are shown.

**Comment by dantleech** [comment]
hmm, I don't get any public methods there.
```
class FooBar implements Foo
{
    public function bar() {}
}

class Bar
{
    private Foo $foo;

    public function __construct(Foo $foo)
    {
        $this->foo = $foo;
    }

    public function foo(): void
    {
        if (!$this->foo instanceof FooBar) {
            return;
        }

        $this->foo->
        // $this is now inferred as FooBar
    }
}
```

**Comment by dantleech** [comment]
Oh ignore that -- the class was implementing a non-existing class. Indeed - I get the public methods.

**Comment by dantleech** [comment]
I guess something is missing. 
image

i guess we use class reflection to get the property types when walking assignments etc.

**Comment by dantleech** [comment]
Let's merge it - it fixes a bug anyway and not sure how easy it would be to fix - probably it needs a wider architectural solution.

**Comment by camilledejoye** [comment]
I think the current fix is enough for now, it covers most of the use cases we will encounter.
So I would not remove it since it does not (yet at least ;) ) bring any bug.
And I agree that some big changes would be needed to make it work in all cases, basically changing how we deal with types in general in the worse-reflection I guess...
Scared just to think about it :smile:

**Comment by dantleech** [comment]
I'm scared about getting everything working on PHP8 and migrating from Travis which is only getting worse it seems.

**Pull request merged**
