### PR TITLE
Extract method text edits

### PR DESCRIPTION
**Pull request by dantleech**
```
  phpactor/code-transform b1bed052..36803c7c                                                                                                            
                                                                                                                                                        
    [2021-05-08 09:32:59] f4d4ab09 dantleech Added missing method finder (#49)                                                                          
    [2021-05-08 10:43:44] 855da023 dantleech Improved tests                                                                                             
    [2021-05-08 10:44:54] fbb73f5b dantleech Add guard clause                                                                                           
    [2021-05-09 14:36:14] fd303bcd dantleech Reflect class-like                                                                                         
    [2021-05-14 08:00:56] 36803c7c BladeMF Change ExtractMethod return value ...                                                                        
                                                                                                                                                        
  phpactor/code-transform-extension c76913c6..aff7ebc4                                                                                                  
                                                                                                                                                        
    [2021-05-08 09:37:43] aff7ebc4 dantleech Add missing method finder                                                                                  
                                                                                                                                                        
  phpactor/language-server-phpactor-extensions 1ca1b27a..f1661d1d                                                                                       
                                                                                                                                                        
    [2021-05-09 13:46:26] aa407451 dantleech Generate method (#40)  * WIP gen...                                                                        
    [2021-05-09 14:40:04] bb351376 dantleech Use located document to convert ...                                                                        
    [2021-05-14 08:08:38] f1661d1d dantleech Extract method (#42)  * Extract ...                                                                        
                                                                                                                                                        
  phpactor/worse-reflection ba68c3e8..159d404f                                                                                                          
                                                                                                                                                        
    [2021-05-09 12:53:43] c6382629 dantleech Fix progress logger                                                                                        
    [2021-05-09 12:59:19] 159d404f dantleech Force ANSI 
```

### CODE REVIEW

**Comment by dantleech** [comment]
Replaces #1270

**Comment by dantleech** [comment]
I get this error in the language server:
```
[Error  - 12:07:09] Request textDocument/codeAction failed.
  Message: Exception [OutOfBoundsException] Position 45:1 is larger than text length 1179: <?php

namespace PhpBench\Extensions\Html\Tests\Renderer;

use Generator;
use PhpBench\Expression\Printer;
use PhpBench\Extensions\Html\Renderer\HtmlRenderer;
use PhpBench\Extensions\Html\Template\ObjectRenderers;
use PhpBench\Report\Renderer\ConsoleRenderer;
use PhpBench\Report\RendererInterface;
use PhpBench\Tests\TestCase;
use PhpBench\Tests\Unit\Report\Renderer\AbstractRendererCase;
use PhpBench\Tests\Util\Approval;
use Symfony\Component\Console\Output\BufferedOutput;

class HtmlRendererTest extends TestCase
{
    protected function getRenderer(): RendererInterface
    {
        return new HtmlRenderer(new ObjectRenderers([
        ]));
    }

    /**
     * @dataProvider provideRender
     */
    public function testRender(string $path): void
    {
        $approval = Approval::create($path, 2);
        $reports = (new OutputTestGenerator())->generate($collection, new Config('foo', $config));
        $approval->getConfig(0));



        $approval->approve($this->output->fetch());
    }

    public function provideRender(): Generator
    {
        foreach (glob(sprintf('%s/%s/*', __DIR__, 'approval')) as $path) {
            yield [$path];
        }
    }
}
  Code: -32603 
#0 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server-phpactor-extensions/lib/LanguageServerBridge/Converter/PositionConverter.php(38): Phpactor\TextDocument\LineCol->toByteOffset()
#1 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server-phpactor-extensions/lib/LanguageServerCodeTransform/CodeAction/ExtractMethodProvider.php(45): Phpactor\Extension\LanguageServerBridge\Converter\PositionConverter::positionToByteOffset()
#2 /home/daniel/www/phpactor/phpactor/vendor/amphp/amp/lib/functions.php(90): Phpactor\Extension\LanguageServerCodeTransform\CodeAction\ExtractMethodProvider->Phpactor\Extension\LanguageServerCodeTransform\CodeAction\{closure}()
#3 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server-phpactor-extensions/lib/LanguageServerCodeTransform/CodeAction/ExtractMethodProvider.php(66): Amp\call()
#4 /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/CodeAction/AggregateCodeActionProvider.php(30): Phpactor\Extension\LanguageServerCodeTransform\CodeAction\ExtractMethodProvider->provideActionsFor()
```
cc @BladeMF

**Comment by BladeMF** [comment]
That would indicate that the text edits are wrong. They are calculated in the `ExtractMethod` implementation based on the two versions of the source file, right? I think it's either:
* One of the sources is out of date in `ExtractMethod`, or
* The source given to the converter is out of date.

How is this test related? Does it reproduce it?

**Comment by dantleech** [comment]
The above issue is roughly caused by CoC providing the entire document a a range when no range is selected - I think I could fix that.

Another issue is present with the RPC implementation:

```
Phpactor returned an error: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Phpactor\TextDocument\TextDocumentUri::fromString() must be of the type s
tring, null given, called in /home/daniel/www/phpactor/phpactor/vendor/phpactor/code-transform/lib/Adapter/WorseReflection/Refactor/WorseExtractMethod.php on li
ne 158 and defined in /home/daniel/www/phpactor/phpactor/vendor/phpactor/text-document/lib/TextDocumentUri.php:31                                               
Stack trace:                                                                                                                                                    
#0 /home/daniel/www/phpactor/phpactor/vendor/phpactor/code-transform/lib/Adapter/WorseReflection/Refactor/WorseExtractMethod.php(158): Phpactor\TextDocument\Tex
tDocumentUri::fromString()                                                                                                                                      
#1 /home/daniel/www/phpactor/phpactor/lib/Extension/CodeTransformExtra/Rpc/ExtractMethodHandler.php(78): Phpactor\CodeTransform\Adapter\WorseReflection\Refactor
\WorseExtractMethod->extractMethod()                                                                                                                            
#
```

**Comment by BladeMF** [comment]
I'd be grateful if you fixed those.

**Pull request merged**
