### PR TITLE
Using array syntax to destructure

### PR DESCRIPTION
**Pull request by mamazu**
https://wiki.php.net/rfc/short_list_syntax

Some of the codebase already uses it, now everything uses it.

### CODE REVIEW

**Comment by dantleech** [comment]
Pretty sure there is a cs fixer fiz for this?

**Comment by mamazu** [comment]
I tried using rector to get it up to 7.4 standards but that would be too much of a change so I split this up into smaller parts. But if you want I can check if there is a check in the ECS config.

**Comment by dantleech** [comment]
we already use `php-cs-fixer`: https://mlocati.github.io/php-cs-fixer-configurator/#version:3.13|fixerset:@PHP74Migration

**Comment by mamazu** [comment]
Yeah, that doesn't seem to be exhaustive though and it looks like it also only migrates from 7.3 since the feature this branch fixes is a 7.1 feature.

**Comment by dantleech** [comment]
the php-cs-fixer is very minimal at the moment (we are not using many of those "migration" fixes). See https://github.com/phpactor/phpactor/pull/1900 for an example of applying more comprehensive CS rules (didn't merge for other reasons).

**Comment by dantleech** [comment]
In general if we have a CS change it needs to be in cs-fixer.

**Comment by mamazu** [comment]
Yeah, adding a cs rule will also prevent regression. Found the rule and added it.

**Pull request merged**
