### PR TITLE
Include frame state in cache key

### LINKED ISSUE #1522: Cannot complete on arguments defined in lambda functions
For example, in `\Phpactor\Phpactor` please try to complete some public method of Resolver:
```php
        $f = fn (Resolver $resolver) => $resolver->set;
```

### PR DESCRIPTION
**Pull request by dantleech**
Fixes #1522 

Pending performance test

### CODE REVIEW

**Comment by dantleech** [comment]
interestingly the code is faster without the node context cache, the cache seems to have effect on the frame walker:

disabling cache in node context:
```
    test_case_method_frames.................I4 ✔ [Mo0.70ms vs. Mo0.80ms] -12.46% (±2.16%)
```

disabling cache in framewalker:

```
test_case_method_frames.................I4 ✘ [Mo3,112.13ms vs. Mo0.70ms] +446366.51% (±4.56%)
```

**Comment by dantleech** [comment]
```

Table
=====

noframecache
+--------------------------+----------------------------+-----------+--------+--------+--------+--------+-----------+
| benchmark                | subject                    | memory    | min    | max    | mode   | rstdev | stdev     |
+--------------------------+----------------------------+-----------+--------+--------+--------+--------+-----------+
| PhpUnitReflectClassBench | test_case_method_frames () | 215.304mb | 2.573s | 2.942s | 2.767s | ±4.71% | 130.156ms |
+--------------------------+----------------------------+-----------+--------+--------+--------+--------+-----------+

cache
+--------------------------+----------------------------+----------+-----------+-----------+-----------+--------+----------+
| benchmark                | subject                    | memory   | min       | max       | mode      | rstdev | stdev    |
+--------------------------+----------------------------+----------+-----------+-----------+-----------+--------+----------+
| PhpUnitReflectClassBench | test_case_method_frames () | 58.814mb | 631.000μs | 834.000μs | 796.260μs | ±9.99% | 75.727μs |
+--------------------------+----------------------------+----------+-----------+-----------+-----------+--------+----------+

nocache
+--------------------------+----------------------------+-----------+-----------+-----------+-----------+--------+----------+
| benchmark                | subject                    | memory    | min       | max       | mode      | rstdev | stdev    |
+--------------------------+----------------------------+-----------+-----------+-----------+-----------+--------+----------+
| PhpUnitReflectClassBench | test_case_method_frames () | 192.087mb | 633.000μs | 705.000μs | 647.795μs | ±4.34% | 28.994μs |
+--------------------------+----------------------------+-----------+-----------+-----------+-----------+--------+----------+
```

ysing the  node cache saves memory significantly though

**Comment by przepompownia** [comment]
By the way, I haven't noticed a neovim crash recently due to an increase in memory usage (like in https://github.com/phpactor/phpactor/issues/1423).

**Comment by dantleech** [comment]
there was a problem with Phpactor causing NVIM to crash:

- nvim sends `exit notification to Phpactor
- phpactor exits
- phpactor left dangling `inotifywait` process running
- nvim crashed

maybe that was it somehow - it's now mostly fixed as phpactor ensures that inotify is stopped before exiting.

**Comment by przepompownia** [comment]
I will allow myself not to looking for that behavior in details - good to know that it's still possible from other servers. 

In that case crash took place probably on some content changes. It is still strange to me when exit notification could be posted to phpactor. 

Let's put that aside as long as the problem doesn't seem to exist.

**Pull request merged**
