### PR TITLE
README: fix transform anchor

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by dantleech** [comment]
:+1: thanks

**Comment by TomasVotruba** [comment]
You're welcome 👍

**Comment by TomasVotruba** [comment]
Great tool btw 👏 

 I'm working on similar one based in nikic/php-parser

**Comment by dantleech** [comment]
nice, I preferred the tolerant parser in the end as you can traverse to parent nodes which made things much simpler :)

**Comment by TomasVotruba** [comment]
@dantleech That is definitelly a useful feature! Could you link me to that code and method on Github?

**Comment by TomasVotruba** [comment]
I found similar section in nikic/php-parser: https://github.com/nikic/PHP-Parser/blob/master/doc/5_FAQ.markdown#how-can-the-parent-of-a-node-be-obtained

I'd like to inspire, where do you use parent nodes in your code?

**Comment by dantleech** [comment]
Tolerant Parser is [here](https://github.com/Microsoft/tolerant-php-parser), example of getting an ancestor [here](https://github.com/phpactor/worse-reflection/blob/master/lib/Reflection/Inference/FrameBuilder.php#L53).

Also hads lots of helper functions such as `$node->getResolvedNamespace()` to return the fully qualified name of, f.e., a class.

**Comment by TomasVotruba** [comment]
@dantleech Thanks. Link goes to empty line. Where exactly that should go?

> Also hads lots of helper functions such as $node->getResolvedNamespace() to return the fully qualified name of, f.e., a class.

Nice. I'm have a prejudice to Microsoft products, because in my experience it fails in time.
On the other hand, I have good experience with nikic in many other projects.

**Comment by dantleech** [comment]
4 lines above it. I am also skeptical about that company, but the Tolerant parser is a better fit for this project at least.

**Pull request merged**
