### PR TITLE
Generate accessors

### PR DESCRIPTION
**Pull request by dantleech**
https://user-images.githubusercontent.com/530801/158082491-0a5ea9e9-f4a0-4c37-be0d-88081abcf8d2.mp4

### CODE REVIEW

**Comment by grtcdr** [comment]
Woah! Thank you for adding this.

One question though, what command are you calling to show the list of accessors?

**Comment by dantleech** [comment]
Thanks, this is invoking an LSP code action on a sélection. So depends which language server client you use (e.g. coc or neovim LSP, or whatever)

**Comment by grtcdr** [comment]
I'm using neovim's builtin LSP support.

I'll read the docs, thanks for your help :smile:

**Comment by gbprod** [comment]
You should use

```
:'<,'>lua vim.lsp.buf.range_code_action()
```
😉

**Comment by grtcdr** [comment]
That worked very nicely, although I don't get a popup as shown in the video, instead I get prompted to enter a number through the minibuffer. My configuration only has the bare minimum, so I suspect that's why.

**Comment by dantleech** [comment]
see these two config options: https://phpactor.readthedocs.io/en/master/reference/configuration.html#code-transform-refactor-generate-accessor-prefix :)

**Comment by dantleech** [comment]
> I don't get a popup as shown in the video,
that's because I'm using CoC, haven't tried the neovim client before.

**Comment by grtcdr** [comment]
> see these two config options

Thank you, I'll add it to my config.

> that's because I'm using CoC, haven't tried the neovim client before.

I see.

Thank you, once again, for all your help! :)

**Comment by camilledejoye** [comment]
You can look towards either https://github.com/glepnir/lspsaga.nvim or https://github.com/nvim-telescope/telescope.nvim for the popup effect.
lspsaga was not updated for a while but a fork which is up to date exists.

**Pull request merged**
