### PR TITLE
Adding types to all parameters that could be typed

### PR DESCRIPTION
**Pull request by mamazu**

### CODE REVIEW

**Review by dantleech — APPROVED** [review]

**Comment by mamazu** [comment]
Okay, I have no idea why this pipeline failed. I think I caught all errors with floats in the config.

**Comment by dantleech** [comment]
Nice work! The failing VIM test could be annoying.. Away from keyboard atm but if there is nothing obvious I'll check later

**Comment by dantleech** [comment]
I think this was due to calling `phpactor set:config ..cache_lifetime 5.0` before the VIM test, which somehow ended up writing an `int` to the config file, I update Container to cast int to float: https://github.com/phpactor/phpactor/pull/2149

**Comment by mamazu** [comment]
Yeah I screwed that up but I couldn't find the place where it was buggy. But thanks for fixing it.

**Pull request closed without merging**
