### PR TITLE
Update deps with fix for relative-path issue

### PR DESCRIPTION
**Pull request by dantleech**

### CODE REVIEW

**Comment by greg0ire** [comment]
Do I wait for you to merge this or am I supposed to checkout this PR locally?

**Comment by dantleech** [comment]
It seems to create issues in WorseReflection (or some other update to the deps does). Feel free to check it out locally to see if it fixes the issue (or just checkout `master` of `class-to-file`).

**Comment by greg0ire** [comment]
That did it! Great job!

**Comment by dantleech** [comment]
Awesome! Will merge when I figure out the WR issue.

**Comment by dantleech** [comment]
Bah, no idea what happened, updated the deps again and it's green..

**Pull request merged**
