### PR TITLE
Generate methods on enum

### PR DESCRIPTION
**Pull request by mamazu**
Fixes: #2409

Adds the ability to generate methods on enum classes if they don't exist. In the process of implementing the feature I found out that phpactor doesn't have a code builder for enum classes which I added. However, the code builder only supports non-backed enums and might break enums that are backed. I'm not sure this is a requirement though or if I should just throw an error if the enum is backed and don't do anything.

### CODE REVIEW

**Comment by dantleech** [comment]
nice :slightly_smiling_face:  can you add a test to see if it breaks backed enums?

**Comment by mamazu** [comment]
Added a test of breaking enums. It breaks different than I expected it to break. And as for the 8.0 phpunit. I don't know why they work differently than the other ones. Does it have anything to do with the enums not being fully supported yet in that version?

**Comment by dantleech** [comment]
probably, you need to skip enum support for 8.0

**Comment by dantleech** [comment]
nice!

**Pull request merged**
