### PR TITLE
Return 0 on ShutdownServer

### LINKED ISSUE #1307: Error 255 on every client exit
I am not sure whether this happens by intent or not. It seems like Phpactor returns a 255 code on exiting the language server.

My Setup
* NeoVim
* Phpactor via https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#phpactor

Steps to reproduce
* Open any php file
* Exit the editor

The shell displays `Client 1 quit with exit code 255 and signal 0`.

Phpactor Log (debug level) says

```
2021-07-14 08:43:27] phpactor.INFO: IN: {"method":"shutdown","jsonrpc":"2.0","id":2} []
[2021-07-14 08:43:27] phpactor.INFO: OUT:  {"id":2,"result":null,"error":null,"jsonrpc":"2.0"} []
[2021-07-14 08:43:27] phpactor.INFO: IN: {"method":"exit","jsonrpc":"2.0"} []
[2021-07-14 08:43:27] phpactor.CRITICAL: Exit called on STDIO connection, exiting the server [] []
```

In my opinion `Exit called on STDIO connection, exiting the server` shouldn't be `CRITICAL` is something to expect and it shouldn't be treated as critical.

Once this has been clarified I could have a look at the code.

### PR DESCRIPTION
**Pull request by weeman1337**
Couldn't find any simple way testing that :( 

closes #1307

### CODE REVIEW

**Comment by dantleech** [comment]
Sorry I merged this but it's wrong.

**Comment by dantleech** [comment]
Reverted. The Application shouldn't know about the language server.

Instead you need to add the try/catch to the `StartCommand` in `language-server-extension`, I think.

**Comment by dantleech** [comment]
Also, it's likely the behavior should really be that the server loop simply finishes on ServerException, then we don't need to try/catch anything. In which case this belongs in the `language-server` package

**Comment by weeman1337** [comment]
Yeah - looked to easy anyway to be the proper solution :)

**Pull request merged**
