### PR TITLE
`ClassRenamer::createNewName`: treat new path with leading `\` as an absolute path

### PR DESCRIPTION
**Pull request by przepompownia**
It depends on https://github.com/phpactor/class-to-file/pull/32

### CODE REVIEW

**Comment by przepompownia** [comment]
At the moment on real instance I have some successful renaming between namespaces. Not sure what is left to do here besides tests.

**Comment by dantleech** [comment]
Just for completeness, can you explain exactly what this change enables? i.e. what doesn't work currently?

**Comment by przepompownia** [comment]
I allows to move class across namespaces if you put `\` at the start. Until now it was only possible to rename class within the same namespace (unless there's something I don't know :grin: ).

**Comment by przepompownia** [comment]
before (on the clone of phpactor):
image
ater: 
image



Probably it need to add some test but at the moment I don't know where.

**Comment by dantleech** [comment]
Oh ok, I didn't realise this was possible in LSP. Which integration are you using?

**Comment by przepompownia** [comment]
What do you mean by integration?

**Comment by przepompownia** [comment]
At the moment I manually copy the namespace (using nvim in terminal makes it easier), then append it after the leading backslash :grin: Not convenient but the benefit from this functionality is still considerable.

**Comment by przepompownia** [comment]
We would consider to allow relative file paths too as the input but I do not know if it breaks LSP assumptions.

**Comment by dantleech** [comment]
I think this work s by accident, the "way" to love files between namespaces is via. the IDE's file browser, which can send willReame events to the LSP. So essentially you just move files in the file tree. NvimTree supports this at least....

**Comment by przepompownia** [comment]
I's not just moving the class file. Don't forget about all available references that are changed in this operation.

**Comment by dantleech** [comment]
Yes both of the options I mention do that :)

**Comment by przepompownia** [comment]
Before answering to your recent message let me put an example - the result of moving `lib/Rename/Model/LocatedTextEditsMap.php` two levels up

```gitstatus
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   lib/Extension/LanguageServerRename/Handler/FileRenameHandler.php
        modified:   lib/Extension/LanguageServerRename/Handler/RenameHandler.php
        modified:   lib/Extension/LanguageServerRename/Tests/Unit/Handler/FileRenameHandlerTest.php
        modified:   lib/Extension/LanguageServerRename/Util/LocatedTextEditConverter.php
        modified:   lib/Rename/Adapter/ClassMover/FileRenamer.php
        modified:   lib/Rename/Model/FileRenamer/TestFileRenamer.php
        deleted:    lib/Rename/Model/LocatedTextEditsMap.php
        modified:   lib/Rename/Tests/Adapter/ClassMover/FileRenamerTest.php
        modified:   lib/Rename/Tests/Adapter/ReferenceFinder/ClassMover/ClassRenamerTest.php
        modified:   lib/Rename/Tests/Adapter/ReferenceFinder/MemberRenamerTest.php
        modified:   lib/Rename/Tests/Adapter/ReferenceFinder/VariableRenamerTest.php

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .phpactor.json
        lib/LocatedTextEditsMap.php
```

```diff
diff --git a/lib/Extension/LanguageServerRename/Handler/FileRenameHandler.php b/lib/Extension/LanguageServerRename/Handler/FileRenameHandler.php
index 0ba32da6..7273fadc 100644
--- a/lib/Extension/LanguageServerRename/Handler/FileRenameHandler.php
+++ b/lib/Extension/LanguageServerRename/Handler/FileRenameHandler.php
@@ -5,7 +5,7 @@ namespace Phpactor\Extension\LanguageServerRename\Handler;
 use Amp\Promise;
 use Phpactor\LanguageServerProtocol\FileOperationOptions;
 use Phpactor\Rename\Model\FileRenamer;
-use Phpactor\Rename\Model\LocatedTextEditsMap;
+use Phpactor\LocatedTextEditsMap;
 use Phpactor\Extension\LanguageServerRename\Util\LocatedTextEditConverter;
 use Phpactor\LanguageServerProtocol\FileOperationFilter;
 use Phpactor\LanguageServerProtocol\FileOperationPattern;
diff --git a/lib/Extension/LanguageServerRename/Handler/RenameHandler.php b/lib/Extension/LanguageServerRename/Handler/RenameHandler.php
index f58f04e3..f426932b 100644
--- a/lib/Extension/LanguageServerRename/Handler/RenameHandler.php
+++ b/lib/Extension/LanguageServerRename/Handler/RenameHandler.php
@@ -7,7 +7,7 @@ use Phpactor\Extension\LanguageServerBridge\Converter\PositionConverter;
 use Phpactor\Extension\LanguageServerBridge\Converter\RangeConverter;
 use Phpactor\Rename\Model\Exception\CouldNotRename;
 use Phpactor\Rename\Model\LocatedTextEdit;
-use Phpactor\Rename\Model\LocatedTextEditsMap;
+use Phpactor\LocatedTextEditsMap;
 use Phpactor\Rename\Model\RenameResult;
 use Phpactor\Rename\Model\Renamer;
 use Phpactor\Extension\LanguageServerRename\Util\LocatedTextEditConverter;
diff --git a/lib/Extension/LanguageServerRename/Tests/Unit/Handler/FileRenameHandlerTest.php b/lib/Extension/LanguageServerRename/Tests/Unit/Handler/FileRenameHandlerTest.php
index c2c4b5b2..7c097c55 100644
--- a/lib/Extension/LanguageServerRename/Tests/Unit/Handler/FileRenameHandlerTest.php
+++ b/lib/Extension/LanguageServerRename/Tests/Unit/Handler/FileRenameHandlerTest.php
@@ -5,7 +5,7 @@ namespace Phpactor\Extension\LanguageServerRename\Tests\Unit\Handler;
 use Phpactor\Extension\LanguageServerBridge\TextDocument\WorkspaceTextDocumentLocator;
 use Phpactor\Extension\LanguageServerRename\Handler\FileRenameHandler;
 use Phpactor\Rename\Model\FileRenamer\TestFileRenamer;
-use Phpactor\Rename\Model\LocatedTextEditsMap;
+use Phpactor\LocatedTextEditsMap;
 use Phpactor\Extension\LanguageServerRename\Tests\IntegrationTestCase;
 use Phpactor\Extension\LanguageServerRename\Util\LocatedTextEditConverter;
 use Phpactor\LanguageServerProtocol\FileOperationRegistrationOptions;
diff --git a/lib/Extension/LanguageServerRename/Util/LocatedTextEditConverter.php b/lib/Extension/LanguageServerRename/Util/LocatedTextEditConverter.php
index a897bc63..97cf0e09 100644
--- a/lib/Extension/LanguageServerRename/Util/LocatedTextEditConverter.php
+++ b/lib/Extension/LanguageServerRename/Util/LocatedTextEditConverter.php
@@ -4,7 +4,7 @@ namespace Phpactor\Extension\LanguageServerRename\Util;
 
 use Phpactor\Extension\LanguageServerBridge\Converter\TextEditConverter;
 use Phpactor\LanguageServerProtocol\OptionalVersionedTextDocumentIdentifier;
-use Phpactor\Rename\Model\LocatedTextEditsMap;
+use Phpactor\LocatedTextEditsMap;
 use Phpactor\Rename\Model\RenameResult;
 use Phpactor\LanguageServerProtocol\RenameFile;
 use Phpactor\LanguageServerProtocol\TextDocumentEdit;
diff --git a/lib/Rename/Adapter/ClassMover/FileRenamer.php b/lib/Rename/Adapter/ClassMover/FileRenamer.php
index 6a20f119..947a3f49 100644
--- a/lib/Rename/Adapter/ClassMover/FileRenamer.php
+++ b/lib/Rename/Adapter/ClassMover/FileRenamer.php
@@ -9,7 +9,7 @@ use Phpactor\Rename\Model\Exception\CouldNotConvertUriToClass;
 use Phpactor\Rename\Model\Exception\CouldNotRename;
 use Phpactor\Rename\Model\FileRenamer as PhpactorFileRenamer;
 use Phpactor\Rename\Model\LocatedTextEdit;
-use Phpactor\Rename\Model\LocatedTextEditsMap;
+use Phpactor\LocatedTextEditsMap;
 use Phpactor\Rename\Model\UriToNameConverter;
 use Phpactor\TextDocument\Exception\TextDocumentNotFound;
 use Phpactor\TextDocument\TextDocumentLocator;
diff --git a/lib/Rename/Model/FileRenamer/TestFileRenamer.php b/lib/Rename/Model/FileRenamer/TestFileRenamer.php
index 1504570c..c41868d7 100644
--- a/lib/Rename/Model/FileRenamer/TestFileRenamer.php
+++ b/lib/Rename/Model/FileRenamer/TestFileRenamer.php
@@ -7,7 +7,7 @@ use Amp\Promise;
 use Amp\Success;
 use Phpactor\Rename\Model\Exception\CouldNotRename;
 use Phpactor\Rename\Model\FileRenamer;
-use Phpactor\Rename\Model\LocatedTextEditsMap;
+use Phpactor\LocatedTextEditsMap;
 use Phpactor\TextDocument\TextDocumentUri;
 
 class TestFileRenamer implements FileRenamer
diff --git a/lib/Rename/Model/LocatedTextEditsMap.php b/lib/Rename/Model/LocatedTextEditsMap.php
deleted file mode 100644
index 4c093327..00000000
--- a/lib/Rename/Model/LocatedTextEditsMap.php
+++ /dev/null
@@ -1,75 +0,0 @@
-<?php
-
-namespace Phpactor\Rename\Model;
-
-use Phpactor\TextDocument\TextDocumentUri;
-use Phpactor\TextDocument\TextEdits;
-
-final class LocatedTextEditsMap
-{
-    /**
-     * @param array<string,TextEdits> $map
-     */
-    public function __construct(private array $map)
-    {
-    }
-
-    public static function create(): self
-    {
-        return new self([]);
-    }
-
-    /**
-     * @param LocatedTextEdit[] $locatedEdits
-     */
-    public static function fromLocatedEdits(array $locatedEdits): self
-    {
-        $map = new self([]);
-        foreach ($locatedEdits as $locationEdit) {
-            $map = $map->withTextEdit($locationEdit);
-        }
-
-        return $map;
-    }
-
-    public function withTextEdit(LocatedTextEdit $edit): self
-    {
-        $map = $this->map;
-        $uri = $edit->documentUri();
-        $edit = $edit->textEdit();
-
-        if (!isset($map[$uri->__toString()])) {
-            $map[$uri->__toString()] = new TextEdits();
-        }
-
-        $map[$uri->__toString()] = $map[$uri->__toString()]->add($edit);
-
-        return new self($map);
-    }
-
-    public function merge(self $map): self
-    {
-        $me = $this;
-
-        foreach ($map->toLocatedTextEdits() as $textEdit) {
-            foreach ($textEdit->textEdits() as $edit) {
-                $me = $me->withTextEdit(new LocatedTextEdit($textEdit->documentUri(), $edit));
-            }
-        }
-
-        return $me;
-    }
-
-    /**
-     * @return LocatedTextEdits[]
-     */
-    public function toLocatedTextEdits(): array
-    {
-        $locatedTextEdits = [];
-        foreach ($this->map as $uri => $edits) {
-            $locatedTextEdits[] = new LocatedTextEdits($edits, TextDocumentUri::fromString($uri));
-        }
-
-        return $locatedTextEdits;
-    }
-}
diff --git a/lib/Rename/Tests/Adapter/ClassMover/FileRenamerTest.php b/lib/Rename/Tests/Adapter/ClassMover/FileRenamerTest.php
index 7950d14b..7afd8625 100644
--- a/lib/Rename/Tests/Adapter/ClassMover/FileRenamerTest.php
+++ b/lib/Rename/Tests/Adapter/ClassMover/FileRenamerTest.php
@@ -7,7 +7,7 @@ use Phpactor\ClassMover\ClassMover;
 use Phpactor\Indexer\Model\Record;
 use Phpactor\Rename\Adapter\ClassMover\FileRenamer;
 use Phpactor\Rename\Adapter\ClassToFile\ClassToFileUriToNameConverter;
-use Phpactor\Rename\Model\LocatedTextEditsMap;
+use Phpactor\LocatedTextEditsMap;
 use Phpactor\Extension\LanguageServerRename\Tests\IntegrationTestCase;
 use Phpactor\Indexer\Adapter\Php\InMemory\InMemoryIndex;
 use Phpactor\Indexer\Model\QueryClient;
diff --git a/lib/Rename/Tests/Adapter/ReferenceFinder/ClassMover/ClassRenamerTest.php b/lib/Rename/Tests/Adapter/ReferenceFinder/ClassMover/ClassRenamerTest.php
index 6ef9f8a7..6a9f2cf2 100644
--- a/lib/Rename/Tests/Adapter/ReferenceFinder/ClassMover/ClassRenamerTest.php
+++ b/lib/Rename/Tests/Adapter/ReferenceFinder/ClassMover/ClassRenamerTest.php
@@ -7,7 +7,7 @@ use Microsoft\PhpParser\Parser;
 use Phpactor\ClassMover\ClassMover;
 use Phpactor\Rename\Adapter\ReferenceFinder\ClassMover\ClassRenamer;
 use Phpactor\Rename\Model\LocatedTextEdits;
-use Phpactor\Rename\Model\LocatedTextEditsMap;
+use Phpactor\LocatedTextEditsMap;
 use Phpactor\Rename\Model\NameToUriConverter;
 use Phpactor\Rename\Tests\Adapter\ReferenceFinder\ReferenceRenamerIntegrationTestCase;
 use Phpactor\Extension\LanguageServerRename\Tests\Util\OffsetExtractor;
diff --git a/lib/Rename/Tests/Adapter/ReferenceFinder/MemberRenamerTest.php b/lib/Rename/Tests/Adapter/ReferenceFinder/MemberRenamerTest.php
index 1af833f8..959d7c85 100644
--- a/lib/Rename/Tests/Adapter/ReferenceFinder/MemberRenamerTest.php
+++ b/lib/Rename/Tests/Adapter/ReferenceFinder/MemberRenamerTest.php
@@ -9,7 +9,7 @@ use Phpactor\Extension\LanguageServerRename\Tests\Unit\PredefiniedImplementation
 use Phpactor\Extension\LanguageServerRename\Tests\Util\OffsetExtractor;
 use Phpactor\Rename\Adapter\ReferenceFinder\MemberRenamer;
 use Phpactor\Rename\Model\LocatedTextEdits;
-use Phpactor\Rename\Model\LocatedTextEditsMap;
+use Phpactor\LocatedTextEditsMap;
 use Phpactor\ReferenceFinder\PotentialLocation;
 use Phpactor\Rename\Model\ReferenceFinder\PredefinedReferenceFinder;
 use Phpactor\TextDocument\ByteOffset;
diff --git a/lib/Rename/Tests/Adapter/ReferenceFinder/VariableRenamerTest.php b/lib/Rename/Tests/Adapter/ReferenceFinder/VariableRenamerTest.php
index ed43c89a..8f725ea3 100644
--- a/lib/Rename/Tests/Adapter/ReferenceFinder/VariableRenamerTest.php
+++ b/lib/Rename/Tests/Adapter/ReferenceFinder/VariableRenamerTest.php
@@ -7,7 +7,7 @@ use PHPUnit\Framework\TestCase;
 use Generator;
 use Phpactor\Rename\Adapter\ReferenceFinder\VariableRenamer;
 use Phpactor\Rename\Model\LocatedTextEdits;
-use Phpactor\Rename\Model\LocatedTextEditsMap;
+use Phpactor\LocatedTextEditsMap;
 use Phpactor\Extension\LanguageServerRename\Tests\Util\OffsetExtractor;
 use Phpactor\ReferenceFinder\DefinitionAndReferenceFinder;
 use Phpactor\ReferenceFinder\PotentialLocation;
```

**Comment by przepompownia** [comment]
I have been using nvim-tree for over a year but didn't find how would it be able to make such an edit like on the example above. 

I don't forget about RPC commands but usually I have configured the server using `init_options` as much as possible. For some options `.phpactor.json` is still needed but I'd like to not duplicate configuration.

**Comment by dantleech** [comment]
I'll new to check my config and refresh my memory. It's certainly how it's _supposed_ to work.

**Comment by przepompownia** [comment]
Regardless of useful alternatives why not to have such possibility? It doesn't exceed LSP. Only input method is not as convenient as entering file path (with completion).

**Comment by dantleech** [comment]
I need to check, as I understood it as rename symbol, not "move file" - I'm surprised it works :)

**Comment by przepompownia** [comment]
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#renameParams

In  `newName` needs to be a string, nothing more. FQCN with leading backslash does not break this rule.

**Comment by przepompownia** [comment]
I also started to look at `workspace/willRenameFiles` request in phpactor, but let's discuss about possible bug it in a separate issue.

**Comment by dantleech** [comment]
closing for now as I'd rather avoid adding support for (as far as I understand it) unsupported workflows

**Pull request closed without merging**
