### PR TITLE
ContextMenuHandler looks for the closest resolvable node

### LINKED ISSUE #777: Context menu: Unknown symbol (or whitespace) should assume parent context.
e.g. if invoking context menu on whitespace in between class members, assume the context is "class".

### PR DESCRIPTION
**Pull request by elythyr**
Fixes #777 

I guess it's more a feature than a bugfiix but whatever :)

### CODE REVIEW

**Comment by dantleech** [comment]
hmm, I can't reproduce the fix based on the ticket (invoking context menu in empty space), and there is a third argument to `reflectOffset` ... is something missing?

**Comment by elythyr** [comment]
Will look into it tomorrow

**Comment by elythyr** [comment]
Just made https://github.com/phpactor/worse-reflection/pull/57
Which is the missing part that explains why it was not working.
The only changes here are the fact that we use the position of the reflected offset instead of the one provided to the handler, since the node resolver will return the closest node to the offset instead of the node of the offset if it is unknown.

**Comment by dantleech** [comment]
We could update this to use the suggested [interesting offset finder](https://github.com/phpactor/code-transform/pull/26).

**Comment by elythyr** [comment]
Yes, I may have talk about it here instead of in the worse-reflection package.
As soon I will have the time to make it work I will close the PR in the worse-reflection package and update this one.

**Comment by elythyr** [comment]
Hi,

I'm working on closing this feature.
Already make a few comments on related PR in others repositories.
For this one we have to merge https://github.com/phpactor/code-transform/pull/26 before.
And another one I will open on https://github.com/phpactor/code-transform-extension, I will update this message once the PR will be created.
The PR will register the Interesting offset finder as a service on the extension and allow us to it here for the ContextMenuHandler.

**Comment by elythyr** [comment]
@ping composer.lock updated to take the new changes into account
The CI should not be an issue

**Comment by dantleech** [comment]
Seems to be an issue:

```
Phpactor\Tests\Unit\Extension\ContextMenu\Handler\ContextMenuHandlerTest::testNoActionsAvailable
405TypeError: Argument 2 passed to Phpactor\Extension\ContextMenu\Handler\ContextMenuHandler::__construct() must implement interface Phpactor\CodeTransform\Domain\Helper\InterestingOffsetFinder, instance of Double\Phpactor\Extension\Core\Application\Helper\ClassFileNormalizer\P53 given, called in /home/travis/build/phpactor/phpactor/tests/Unit/Extension/ContextMenu/Handler/ContextMenuHandlerTest.php on line 64
406
407
```

**Comment by elythyr** [comment]
My bad didn't checked the unit tests, so used to have a hook on git push...

**Comment by dantleech** [comment]
Have done a qucik manual test:

In `lib/Phpactor.php`:
```php
        $loader = ConfigLoaderBuilder::create()
            ->enableJsonDeserializer('json')
            ->enableYamlDeserializer('yaml')
            ->addXdgCandidate('phpactor', 'phpactor.json', 'json')
            ->addXdgCandidate('phpactor', 'phpactor.yml', 'yaml')
            ->addCandidate($cwd . '/.phpactor.json', 'json')
            ->addCandidate($cwd . '/.phpactor.yml', 'yaml')
            ->loader();
```

Invoking the menu on any of the above methods gives the menu for the `ConfigLoaderBuilder`.

Can you reproduce? Seems to be the case for all methods calls.

**Comment by dantleech** [comment]
It's an issue with the offset finder, I tried to fix it this morning but failed, I created a failing test: https://github.com/phpactor/code-transform/pull/28/files.

**Comment by dantleech** [comment]
I fixed this case in code-transform, will test again tomorrow.

**Comment by elythyr** [comment]
Seems to be working on quick tries.
Will see how today goes at work, that will gave me more examples :)
Nice job.

**Comment by dantleech** [comment]
Replacing with #825

**Pull request closed without merging**
