### PR TITLE
Fixing binary path

### PR DESCRIPTION
**Pull request by talbergs**
<a href="https://cl.ly/2o1u2F2R042W" target="_blank"></a>

https://getcomposer.org/doc/articles/vendor-binaries.md

### CODE REVIEW

**Comment by dantleech** [comment]
thanks!

**Comment by talbergs** [comment]
ehh, still the same issue - https://cl.ly/1E470b0y410Z so this didn't fix that.

**Comment by dantleech** [comment]
Are you on the `develop` branch?

**Comment by talbergs** [comment]
yes

**Comment by dantleech** [comment]
Hmm, the screenshot says `dev-master`

I just did:

```
$ composer global require phpactor/phpactor dev-develop
```

and did not get the error you mentioned.

**Comment by talbergs** [comment]
In doing the way you wrote above, all works fine for me now.  Binary is linked, etc ..
I might just be doing something outside composer's conventions here:
I had his in my ~/.composer.json
```
{
    "minimum-stability": "dev",
    "require": {
        "phpactor/phpactor": "dev-master@a6030a5f7a241d3e7a00c94ca65cf9ab586d9c2e"
    }
}
```
just pointing to the sha of the commit (that happens to be in 'develop' branch now) i was interested in.
The files of that commit did checked out thou, that's how I got that message.

Nvm, all good now thx.

**Pull request merged**
