### PR TITLE
Failing tests for multiple references for one FQN

### PR DESCRIPTION
**Pull request by mamazu**

### CODE REVIEW

**Comment by dantleech** [comment]
after implementing this locally I'm not sure we want this behavior, PHPStorm does not support this f.e. and analysing > 1 file for the same class also makes no sense really. the solution is to ignore the `Workspace` class when working in Phpactor to avoid the duplciate PHPUnit TestCase definition.

**Comment by dantleech** [comment]
closing for now...

**Comment by haringsrob** [comment]
I think this was also briefly mentioned in one of the Laravel story. IDE-helpers may document classes that have magic methods. 
Because those classes due to the "stubs" exist in multiple locations phpactor only picks up one of them.

**Comment by dantleech** [comment]
Yes, need to understand better how that works f.e. in phpstorm

**Comment by haringsrob** [comment]
I will check that, I still have my licence

**Pull request closed without merging**
