### PR TITLE
Index infos refactoring

### PR DESCRIPTION
**Pull request by dantleech**
I started to refactor and went down a bit of a rabbit hole and have given up:

- Ask for the index to remove in a loop and re-render the updated list
- Auto-completion for index name / number
- Show last modified and age (the previous version was incorrect)

image

Unfortunately there seems to be a bug in Symonys Section output when used with the Question and the output is corrupted:

image

### CODE REVIEW

**Comment by dantleech** [comment]
cc @mamazu I might need to unpick this and port only the "fixes" back.

**Comment by mamazu** [comment]
Did we want to refactor this to use the file index class anyways?

**Comment by dantleech** [comment]
it would be good to have the abstraction, but might be premature

**Comment by mamazu** [comment]
In this merge request you have removed the function to clean all indicies. Is that on purpose or was that on accident?

**Comment by mamazu** [comment]
In this merge request you have removed the function to clean all indicies. Is that on purpose or was that on accident?

**Comment by dantleech** [comment]
i think i was looking for another way, would have re-included it I think,

**Pull request closed without merging**
