### PR TITLE
Disable XDebug

### PR DESCRIPTION
**Pull request by dantleech**
Following from comment on #317 have tried using the composer library to disable XDebug.

Surprisingly it seems to make no performance difference at all (on my machine):

```
benchmark: ClassSearchBench, subject: benchClassSearch
+--------+--------+------+-----------------------------------------------------+-----------------------------------------------------+
| groups | params | revs | no xdebug                                           | xdebug                                              |
+--------+--------+------+-----------------------------------------------------+-----------------------------------------------------+
|        | []     | 1    | 205,910.200μs                                       | 202,725.500μs                                       |
+--------+--------+------+-----------------------------------------------------+-----------------------------------------------------+

benchmark: CompleteBench, subject: benchComplete
+--------+--------+------+-----------------------------------------------------+-----------------------------------------------------+
| groups | params | revs | no xdebug                                           | xdebug                                              |
+--------+--------+------+-----------------------------------------------------+-----------------------------------------------------+
|        | []     | 1    | 573,967.000μs                                       | 570,346.100μs                                       |
+--------+--------+------+-----------------------------------------------------+-----------------------------------------------------+
```

### CODE REVIEW

**Comment by weirdan** [comment]
Does your benchmark suite actually run that `bin/phpactor` script that you changed? It looks like it foregoes the script file and just instantiates the application class directly?

**Comment by dantleech** [comment]
:thinking:

**Comment by dantleech** [comment]
Yep, thanks. Huge performance difference :)

```
+--------+--------+------+---------------+----------------+
| groups | params | revs | xdebug        | no xdebug      |
+--------+--------+------+---------------+----------------+
|        | []     | 1    | 731,946.055μs | 254,251.397μs  |
+--------+--------+------+---------------+----------------+
```

Note that this includes the process start up time

**Comment by dantleech** [comment]
Although I do see this sometimes:

```
+------------------+------------------+--------+--------+------+-----+------------+-----------------+-----------------+-----------------+-----------------+---------------+--------+-------+
| benchmark        | subject          | groups | params | revs | its | mem_peak   | best            | mean            | mode            | worst           | stdev         | rstdev | diff  |
+------------------+------------------+--------+--------+------+-----+------------+-----------------+-----------------+-----------------+-----------------+---------------+--------+-------+
| CompleteBench    | benchComplete    |        | []     | 1    | 10  | 2,346,024b | 1,207,040.000μs | 1,548,954.500μs | 1,346,293.425μs | 2,155,820.000μs | 328,422.932μs | 21.20% | 5.83x |
| ClassSearchBench | benchClassSearch |        | []     | 1    | 10  | 2,345,520b | 203,793.000μs   | 265,793.000μs   | 242,645.838μs   | 391,093.000μs   | 54,290.430μs  | 20.43% | 1.00x |
+------------------+------------------+--------+--------+------+-----+------------+-----------------+-----------------+-----------------+-----------------+---------------+--------+-------+
```

**Comment by weirdan** [comment]
You mean 2x difference between best & worst runs?

**Comment by dantleech** [comment]
More that the best is 1.3s compared to 0.25s previously, but it isn't consistent (before this PR the time was ~0.5s). Will have to experiment further.

**Comment by dantleech** [comment]
Have updated this and am allowing this feature to be disabled in config if required.

**Comment by dantleech** [comment]
Making again on `develop`

**Pull request closed without merging**
