### PR TITLE
Remove conflict markers and duplicated key

### PR DESCRIPTION
**Pull request by przepompownia**
related #902 

My json linter detected also duplicated key so I removed one of them (that without shortcut key).

### CODE REVIEW

**Comment by dantleech** [comment]
Thanks :) We should really add an integration test for `menu.json`

**Comment by dantleech** [comment]
Doh - there was one: https://travis-ci.org/phpactor/phpactor/jobs/658385930#L392 :man_facepalming: 

Note to self: don't push to develop.

**Comment by przepompownia** [comment]
The test for installing a fully equipped language server will be appreciated too.

**Comment by dantleech** [comment]
We already have that: https://github.com/phpactor/phpactor/blob/develop/config/travis/extensions-to-test

**Pull request merged**
